version: '3.7'
services:
  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
        - VAULT_ADDR=http://127.0.0.1:8200
    volumes:
      - ./volumes/logs:/vault/logs
      - ./volumes/file:/vault/file
      - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json